### ISSUE TITLE
When i call relations with list of fields it throws FatalThrowableError.

### ISSUE THREAD

**Issue by inosjack** [Froiden/laravel-rest-api#2]
When i call relations with list of fields it throws FatalThrowableError.

`$response = $this->call('GET', '/dummyUser',
              [
                  'fields' => "id,name,email,phone",
              ]);
$this->assertEquals(200, $response->status());
`

` <h1>Whoops, looks like something went wrong.</h1>\n
                                        <h2 class="block_exception clear_fix">\n
                            <span class="exception_counter">1/1</span>\n
                            <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalThrowableError">FatalThrowableError</abbr> in <a title="E:\xampp\htdocs\september2016\12september\laravel-rest-api\src\ApiController.php line 549" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ApiController.php line 549</a>:</span>\n
                            <span class="exception_message">Call to a member function setAppends() on null</span>\n
                        </h2>\n
                        <div class="block">\n
                            <ol class="traces list_exception">\n
       <li> in <a title="E:\xampp\htdocs\september2016\12september\laravel-rest-api\src\ApiController.php line 549" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ApiController.php line 549</a></li>\n
       <li>at <abbr title="Froiden\RestAPI\ApiController">ApiController</abbr>->processAppends(<em>object</em>(<abbr title="Illuminate\Database\Eloquent\Collection">Collection</abbr>)) in <a title="E:\xampp\htdocs\september2016\12september\laravel-rest-api\src\ApiController.php line 513" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ApiController.php line 513</a></li>\n
       <li>at <abbr title="Froiden\RestAPI\ApiController">ApiController</abbr>->getResults() in <a title="E:\xampp\htdocs\september2016\12september\laravel-rest-api\src\ApiController.php line 144" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">ApiController.php line 144</a></li>\n
       <li>at <abbr title="Froiden\RestAPI\ApiController">ApiController</abbr>->index()</li>\n
       <li>at <abbr title=""></abbr>call_user_func_array(<em>array</em>(<em>object</em>(<abbr title="Froiden\RestAPI\Tests\Controllers\UserController">UserController</abbr>), 'index'), <em>array</em>()) in <a title="E:\xampp\htdocs\september2016\12september\vendor\laravel\framework\src\Illuminate\Routing\Controller.php line 55" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Controller.php line 55</a></li>\n'

**Comment by shashankkrjain** [comment]
Fixed this issue
