### ISSUE TITLE
Mulitple Filters

### ISSUE THREAD

**Issue by hamza-younas94** [Froiden/laravel-rest-api#22]
HI,

i am trying to use multiple filter but its skipping first filter:

`http://localhost/project/api/v1/cards/department=Production&filters=name lk "BM"`

its giving cars with matching with BM but skipping the column "department"

**Comment by phailee** [comment]
Please check the documentation .You are passing filters wrong. In documentation the example is like[](http://api.example.com/users?filters=status eq "active" or (status eq "suspended" and deleted_at eq null)) .. So pass your filters like this it will work.

**Comment by phailee** [comment]
your request should be 
http://localhost/project/api/v1/cards/?filters=(name lk "BM" and department eq "Production")

**Comment by hamza-younas94** [comment]
@phailee  i did the same but its ignoring department i think you should give it a look.
