### ISSUE TITLE
$id in controller is empty

### ISSUE THREAD

**Issue by slava-vishnyakov** [Froiden/laravel-rest-api#7]
I'm trying `laravel-rest-api` and I've found this change:

https://github.com/Froiden/laravel-rest-api/commit/f39e9f6b5f6670d4af62899abc706f0c6e6f0331

![image](https://cloud.githubusercontent.com/assets/817931/23958376/f7eec130-09b2-11e7-8cf4-26b4e4b152a2.png)

If I dump `func_get_args()` from here - it's an empty array `[]` (with url like `/api/v1/model_name/1`)

As a result I get this

```
ResourceNotFoundException in ApiController.php line 578:
Requested resource not found
```
at `/api/v1/model_name/1`

The route is defined as:

```php
ApiRoute::group(['middleware' => ['api'], 'namespace' => 'App\Http\Controllers'], function () {
    ApiRoute::resource('contract_templates', 'ModelNameController');
});
```

Laravel 5.4.15

If I revert that change (adding $id) - the thing works.

**Comment by shashankkrjain** [comment]
Hi, Thanks for reporting this error. Actually, I have discovered this error myself also. This is happening in Laravel 5.4, works fine on 5.3 and below. I am investigating it and will update when fixed

**Comment by slava-vishnyakov** [comment]
Awesome! Thanks.

Actually, thanks for the library - at first sight it seems excellent! :)

**Comment by slava-vishnyakov** [comment]
Maybe something like this?

```php
use Illuminate\Routing\Route;

....

/**
 * Process the show request
 *
 * @return mixed
 */
public function show(Route $r)
{
    // We need to do this in order to support multiple parameter resource routes. For example,
    // if we map route /user/{user}/comments/{comment} to a controller, Laravel will pass `user`
    // as first argument and `comment` as last argument. So, id object that we want to fetch
    // is the last argument.
    $lastParameterName = last($r->parameterNames());
    $id = $r->parameter($lastParameterName);
```

**Comment by shashankkrjain** [comment]
Actually I fixed this one by adding variable length function arguments like this:

```php
public function destroy(...$args)
```

Your method is also good. I must think over which one to go with :)

**Comment by slava-vishnyakov** [comment]
Excellent! Fixed! Thank you very much! 

Could you also tag it w/something like `1.0.2`?

**Comment by shashankkrjain** [comment]
Yes, I am going to do that. Right now travis ci seems to be failing tests for no reason. I am looking into that.

**Comment by slava-vishnyakov** [comment]
Actually, something else seems to be broken, now
`/api/v1/model_name` shows

```
ReflectionException in RouteDependencyResolverTrait.php line 57:
Internal error: Failed to retrieve the default value
```

```
in RouteDependencyResolverTrait.php line 57
at ReflectionParameter->getDefaultValue() in RouteDependencyResolverTrait.php line 57
at ControllerDispatcher->resolveMethodDependencies(array(), object(ReflectionMethod)) in RouteDependencyResolverTrait.php line 27
at ControllerDispatcher->resolveClassMethodDependencies(array(), object(ModelNameController), 'index') in ControllerDispatcher.php line 40
at ControllerDispatcher->dispatch(object(Route), object(ModelNameController), 'index') in Route.php line 203
at Route->runController() in Route.php line 160
at Route->run() in Router.php line 559
```

91f21a27b32b2893225ee0cfd8afdf2a76deef8d  doesn't have this problem

**Comment by slava-vishnyakov** [comment]
Probably due to this change:
https://github.com/Froiden/laravel-rest-api/commit/50d2b7d8057eaf9b21a30c59c476bf57e80bb10e#diff-6fd089bcc5017cac89ed7cf0ace2e138R144

`index` route doesn't have bindings?

**Comment by shashankkrjain** [comment]
Does your method work properly here?

**Comment by slava-vishnyakov** [comment]
Actually, just changing `index` to `public function index()` (without `...$args`) fixes the problem

**Comment by shashankkrjain** [comment]
I believe `store` method would also have same issue. This method makes is mandatory to pass atleast one argument to function or it would fail.

**Comment by slava-vishnyakov** [comment]
Probably.. didn't get that far in trying the package :)

**Comment by slava-vishnyakov** [comment]
Correct, `store()` also needs to be without args
