### ISSUE TITLE
Laravel 5.4 renamed methods?

### ISSUE THREAD

**Issue by slava-vishnyakov** [Froiden/laravel-rest-api#8]
PHPstorm (reasonably) highlights quite a few methods in Laravel 5.4 that seem to be renamed:

![image](https://cloud.githubusercontent.com/assets/817931/23971049/5a2347f2-09dd-11e7-8e06-40e95afe646a.png)

![image](https://cloud.githubusercontent.com/assets/817931/23971057/61b0b0f4-09dd-11e7-8f82-2739d8be6779.png)

it seems that `getForeignKey` was renamed to `getQualifiedForeignKeyName`

https://github.com/laravel/docs/issues/3017

And `getOtherKey` was renamed to `getOwnerKey`, as it seems:

http://stackoverflow.com/questions/41889566/laravel-5-4-from-5-3-error-getotherkey

**Comment by slava-vishnyakov** [comment]
On the other hand `getOtherKey` might be: 
1) `getQualifiedRelatedKeyName` (in `BelongsToMany`) https://github.com/zofe/rapyd-laravel/pull/394/files
2) `getOwnerKey()` (in `BelongsTo`)

**Comment by slava-vishnyakov** [comment]
(I'm talking about `ApiController`)

**Comment by slava-vishnyakov** [comment]
It also seems that here:

https://github.com/Froiden/laravel-rest-api/blob/master/src/ApiModel.php#L302
`getQualifiedParentKeyName` should be `getQualifiedForeignKeyName`

Without it `ApiModel` sets `id` of foreign model, instead of something like `other_model_id`.

**Comment by shashankkrjain** [comment]
Hi, thanks for the information. I am looking into all these issues, will update asap.

**Comment by shashankkrjain** [comment]
I am open to accepting a PR if you fix the issues and create one :) For the renamed methods, we will need to selectively call the methods according to Laravel version.

**Comment by Kyslik** [comment]
@shashankkrjain 
Hello, just giving you heads up; methods are same for Laravel `5.1` to `5.3` and change is only in Laravel `5.4`

**Comment by shashankkrjain** [comment]
I have removed support for Laravel 5.4 as too many things are breaking right now. I will be working on it and release a properly tested version when ready. Please keep reporting issues as you find them. Thanks.

**Comment by robsontenorio** [comment]
@shashankkrjain this plugin is great! Any chances to be updated to latest laravel version?

**Comment by mgralikowski** [comment]
Hello, 

someone try this lib with L5.5?

**Comment by shashankkrjain** [comment]
Hi, sorry for fixing this late. I have made the latest release for laravel 5.5 now avaiable thanks for work by @phailee. Please refer documentation to install and report if you face any issues.

**Comment by mgralikowski** [comment]
Thanks for update. I have some troubles with dependencies:

>   Problem 1
>     - Installation request for froiden/laravel-rest-api ^3.0 -> satisfiable by froiden/laravel-rest-api[3.0.1].
>     - froiden/laravel-rest-api 3.0.1 requires phpunit/phpunit ^4.8 || ^5.0 -> no matching package found.
