### ISSUE TITLE
Error filtering relations

### ISSUE THREAD

**Issue by qadirpervez** [Froiden/laravel-rest-api#9]
`fields: 'id,post_title,users{id,user_id},users:user{id,first_name,last_name,username}`
when i fetch results its fine even when i use filter
`filter: 'post_title' lk " ${query} "` it works but when i do something like
`filter: 'users:user{first_name}' lk " ${query} "` because i am searching bu user first name it is not working.
Is there a way of doing this or am I doing it wrong?

**Comment by shashankkrjain** [comment]
filtering on relations is not currently supported.
